# version: "3.9"

services:

  scraper:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    container_name: manga_scraper
    volumes:  
      - .:/app
    working_dir: /app/ingestion 
    command: tail -f /dev/null
    networks:
      - manga-network

# ==============================================
# SERVICE : POSTGRESQL 
# ==============================================
  postgres:
    image: postgres:15
    container_name: manga_postgres
    environment:
      POSTGRES_USER: manga
      POSTGRES_PASSWORD: manga12
      POSTGRES_DB: manga_db
    ports:
      - "5432:5432"
    networks:
      - manga-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U manga -d manga_db"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - manga-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - manga-network

  spark-master:
    build:
      context: ./processing
      dockerfile: Dockerfile
    container_name: manga_spark_master
    environment:
      - SPARK_MASTER_HOST=spark-master
      # - SPARK_MASTER_PORT=7077
      - NAMENODE_HOST=namenode
      - SPARK_ROLE=master
    ports:
      - "8080:8080" # Interface Web pour voir tes jobs
      - "7077:7077"
    volumes:
      - ./data_lake:/opt/spark/data_lake
    networks:
      - manga-network

  spark-worker:
    build:
      context: ./processing
      dockerfile: Dockerfile
    container_name: manga_spark_worker
    environment:
      - SPARK_ROLE=worker
      - SPARK_MASTER_HOST=spark-master
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./data_lake:/opt/spark/data_lake
    networks:
      - manga-network


networks:
  manga-network: